config/routes.rb
Rails.application.routes.draw do
  get 'reports/daily'
  get 'reports/weekly'
  get 'loads/daily'
  post 'loads/daily', to: "loads#create_daily", as: "loads_create_daily"
  get 'loads/weekly'
  post 'loads/weekly', to: "loads#create_weekly", as: "loads_create_weekly"
  resources :vacations
  resources :consultants
  resources :teams
  resources :reasons
  resources :days
  resources :weeks
  resources :months
  resources :years
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultant.rb
class Consultant < ApplicationRecord
  enum is_active: { inactive: 0, active: 1 }

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :team
  has_many :daily_hours
  has_many :vacations
end

app/models/daily_hour.rb
class DailyHour < ApplicationRecord
  belongs_to :day
  belongs_to :consultant
end

app/models/day.rb
class Day < ApplicationRecord
  enum is_weekend: { no: 0, yes: 1 }

  belongs_to :week
  belongs_to :month
end

app/models/month.rb
class Month < ApplicationRecord
  belongs_to :year
end

app/models/reason.rb
class Reason < ApplicationRecord
  extend FriendlyId
  friendly_id :reason, use: :slugged
end

app/models/team.rb
class Team < ApplicationRecord
  extend FriendlyId
  friendly_id :team, use: :slugged
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :day
  belongs_to :consultant
  belongs_to :reason
end

app/models/week.rb
class Week < ApplicationRecord
end

app/models/weekly_hour.rb
class WeeklyHour < ApplicationRecord
  belongs_to :day
  belongs_to :consultant
end

app/models/year.rb
class Year < ApplicationRecord
end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
  before_action :set_consultant, only: [:show, :edit, :update, :destroy]

  # GET /consultants
  # GET /consultants.json
  def index
    @consultants = Consultant.all.includes(:team).order(:team_id, :name)
  end

  # GET /consultants/1
  # GET /consultants/1.json
  def show
  end

  # GET /consultants/new
  def new
    @consultant = Consultant.new
  end

  # GET /consultants/1/edit
  def edit
  end

  # POST /consultants
  # POST /consultants.json
  def create
    @consultant = Consultant.new(consultant_params)

    respond_to do |format|
      if @consultant.save
        format.html { redirect_to @consultant, notice: 'Consultant was successfully created.' }
        format.json { render :show, status: :created, location: @consultant }
      else
        format.html { render :new }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultants/1
  # PATCH/PUT /consultants/1.json
  def update
    respond_to do |format|
      if @consultant.update(consultant_params)
        format.html { redirect_to @consultant, notice: 'Consultant was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultant }
      else
        format.html { render :edit }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultants/1
  # DELETE /consultants/1.json
  def destroy
    @consultant.destroy
    respond_to do |format|
      format.html { redirect_to consultants_url, notice: 'Consultant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultant
      @consultant = Consultant.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consultant_params
      params.require(:consultant).permit(:team_id, :name, :is_active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/consultants/_form.html.erb
<%= form_with(model: consultant) do |form| %>
  <% if consultant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consultant.errors.count, "error") %> prohibited this consultant from being saved:</h2>

      <ul>
        <% consultant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.collection_select :team_id, Team.all, :id, :team %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.text_field :is_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/consultants/edit.html.erb
<h1>Editing Consultant</h1>

<%= render 'form', consultant: @consultant %>

<%= link_to 'Show', @consultant %> |
<%= link_to 'Back', consultants_path %>

app/views/consultants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Consultants</h1>

<table>
  <thead>
    <tr>
      <th width="25%">Team</th>
      <th width="50%">Name</th>
      <th width="25%" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <%
    @consultants.each do |consultant|
      tr_class = ""
      if consultant.is_active == 'inactive'
        tr_class = "table-warning"
      end      
    %>
      <tr class="<%= tr_class %>">
        <td><%= consultant.team.team %></td>
        <td><%= consultant.name %></td>
        <td><%= link_to "<i class='fas fa-eye'></i> Show".html_safe, consultant, class: "btn btn-info" %></td>
        <td><%= link_to "<i class='fas fa-edit'></i> Edit".html_safe, edit_consultant_path(consultant), class: "btn btn-warning" %></td>
        <td><%= link_to "<i class='fas fa-trash-alt'></i> Delete".html_safe, consultant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "<i class='fas fa-plus'></i> New Consultant".html_safe, new_consultant_path, class: "btn btn-block btn-success" %>

app/views/consultants/new.html.erb
<h1>New Consultant</h1>

<%= render 'form', consultant: @consultant %>

<%= link_to 'Back', consultants_path %>

app/views/consultants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @consultant.team.team %>
</p>

<p>
  <strong>Name:</strong>
  <%= @consultant.name %>
</p>

<p>
  <strong>Is Active:</strong>
  <%= @consultant.is_active %>
</p>

<%= link_to 'Edit', edit_consultant_path(@consultant) %> |
<%= link_to 'Back', consultants_path %>