config/routes.rb
Rails.application.routes.draw do
  get 'reports/daily'
  get 'reports/weekly'
  get 'loads/daily'
  post 'loads/daily', to: "loads#create_daily", as: "loads_create_daily"
  get 'loads/weekly'
  post 'loads/weekly', to: "loads#create_weekly", as: "loads_create_weekly"
  resources :vacations
  resources :consultants
  resources :teams
  resources :reasons
  resources :days
  resources :weeks
  resources :months
  resources :years
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultant.rb
class Consultant < ApplicationRecord
  enum is_active: { inactive: 0, active: 1 }

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :team
  has_many :daily_hours
  has_many :vacations
end

app/models/daily_hour.rb
class DailyHour < ApplicationRecord
  belongs_to :day
  belongs_to :consultant
end

app/models/day.rb
class Day < ApplicationRecord
  enum is_weekend: { no: 0, yes: 1 }

  belongs_to :week
  belongs_to :month
end

app/models/month.rb
class Month < ApplicationRecord
  belongs_to :year
end

app/models/reason.rb
class Reason < ApplicationRecord
  extend FriendlyId
  friendly_id :reason, use: :slugged
end

app/models/team.rb
class Team < ApplicationRecord
  extend FriendlyId
  friendly_id :team, use: :slugged
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :day
  belongs_to :consultant
  belongs_to :reason
end

app/models/week.rb
class Week < ApplicationRecord
end

app/models/weekly_hour.rb
class WeeklyHour < ApplicationRecord
  belongs_to :day
  belongs_to :consultant
end

app/models/year.rb
class Year < ApplicationRecord
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :set_vacation, only: [:show, :edit, :update, :destroy]
  before_action :set_vars, only: [:new, :edit]

  # GET /vacations
  # GET /vacations.json
  def index
    @vacations = Vacation.order(:day_id).order(:consultant_id)
  end

  # GET /vacations/1
  # GET /vacations/1.json
  def show
  end

  # GET /vacations/new
  def new
    @vacation = Vacation.new
  end

  # GET /vacations/1/edit
  def edit
  end

  # POST /vacations
  # POST /vacations.json
  def create
    @vacation = Vacation.new(vacation_params)

    respond_to do |format|
      if @vacation.save
        format.html { redirect_to @vacation, notice: 'Vacation was successfully created.' }
        format.json { render :show, status: :created, location: @vacation }
      else
        format.html { render :new }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacations/1
  # PATCH/PUT /vacations/1.json
  def update
    respond_to do |format|
      if @vacation.update(vacation_params)
        format.html { redirect_to @vacation, notice: 'Vacation was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacation }
      else
        format.html { render :edit }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacations/1
  # DELETE /vacations/1.json
  def destroy
    @vacation.destroy
    respond_to do |format|
      format.html { redirect_to vacations_url, notice: 'Vacation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation
      @vacation = Vacation.find(params[:id])
    end

    # Create var contents for combo box
    def set_vars
      @days = Day.all
      @consultants = Consultant.where({is_active: 1}).order(:name)
      @reasons = Reason.all
    end

    # Only allow a list of trusted parameters through.
    def vacation_params
      params.require(:vacation).permit(:day_id, :consultant_id, :reason_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/vacations/_form.html.erb
<%= form_with(model: vacation) do |form| %>
  <% if vacation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vacation.errors.count, "error") %> prohibited this vacation from being saved:</h2>

      <ul>
        <% vacation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day_id %>
    <%= form.collection_select :day_id, @days, :id, :date_str %>
  </div>

  <div class="field">
    <%= form.label :consultant_id %>
    <%= form.collection_select :consultant_id, @consultants, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :reason_id %>
    <%= form.collection_select :reason_id, @reasons, :id, :reason %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vacations/edit.html.erb
<h1>Editing Vacation</h1>

<%= render 'form', vacation: @vacation %>

<%= link_to 'Show', @vacation %> |
<%= link_to 'Back', vacations_path %>

app/views/vacations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacations</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Consultant</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacations.each do |vacation| %>
      <tr>
        <td><%= vacation.day.date_str %></td>
        <td><%= vacation.consultant.name %></td>
        <td><%= vacation.reason.reason %></td>
        <td><%= link_to 'Show', vacation %></td>
        <td><%= link_to 'Edit', edit_vacation_path(vacation) %></td>
        <td><%= link_to 'Destroy', vacation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacation', new_vacation_path %>

app/views/vacations/new.html.erb
<h1>New Vacation</h1>

<%= render 'form', vacation: @vacation %>

<%= link_to 'Back', vacations_path %>

app/views/vacations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @vacation.day.date_str %>
</p>

<p>
  <strong>Consultant:</strong>
  <%= @vacation.consultant.name %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @vacation.reason.reason %>
</p>

<%= link_to 'Edit', edit_vacation_path(@vacation) %> |
<%= link_to 'Back', vacations_path %>