config/routes.rb
Rails.application.routes.draw do
  get 'reports/daily'
  get 'reports/weekly'
  get 'loads/daily'
  post 'loads/daily', to: "loads#create_daily", as: "loads_create_daily"
  get 'loads/weekly'
  post 'loads/weekly', to: "loads#create_weekly", as: "loads_create_weekly"
  resources :vacations
  resources :consultants
  resources :teams
  resources :reasons
  resources :days
  resources :weeks
  resources :months
  resources :years
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultant.rb
class Consultant < ApplicationRecord
  enum is_active: { inactive: 0, active: 1 }

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :team
  has_many :daily_hours
  has_many :vacations
end

app/models/daily_hour.rb
class DailyHour < ApplicationRecord
  belongs_to :day
  belongs_to :consultant
end

app/models/day.rb
class Day < ApplicationRecord
  enum is_weekend: { no: 0, yes: 1 }

  belongs_to :week
  belongs_to :month
end

app/models/month.rb
class Month < ApplicationRecord
  belongs_to :year
end

app/models/reason.rb
class Reason < ApplicationRecord
  extend FriendlyId
  friendly_id :reason, use: :slugged
end

app/models/team.rb
class Team < ApplicationRecord
  extend FriendlyId
  friendly_id :team, use: :slugged
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :day
  belongs_to :consultant
  belongs_to :reason
end

app/models/week.rb
class Week < ApplicationRecord
end

app/models/weekly_hour.rb
class WeeklyHour < ApplicationRecord
  belongs_to :day
  belongs_to :consultant
end

app/models/year.rb
class Year < ApplicationRecord
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  before_action :set_reason, only: [:show, :edit, :update, :destroy]

  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.all
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
  end

  # GET /reasons/new
  def new
    @reason = Reason.new
  end

  # GET /reasons/1/edit
  def edit
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @reason = Reason.new(reason_params)

    respond_to do |format|
      if @reason.save
        format.html { redirect_to @reason, notice: 'Reason was successfully created.' }
        format.json { render :show, status: :created, location: @reason }
      else
        format.html { render :new }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reasons/1
  # PATCH/PUT /reasons/1.json
  def update
    respond_to do |format|
      if @reason.update(reason_params)
        format.html { redirect_to @reason, notice: 'Reason was successfully updated.' }
        format.json { render :show, status: :ok, location: @reason }
      else
        format.html { render :edit }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason.destroy
    respond_to do |format|
      format.html { redirect_to reasons_url, notice: 'Reason was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reason
      @reason = Reason.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reason_params
      params.require(:reason).permit(:reason)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/reasons/_form.html.erb
<%= form_with(model: reason) do |form| %>
  <% if reason.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reason.errors.count, "error") %> prohibited this reason from being saved:</h2>

      <ul>
        <% reason.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_field :reason %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reasons/edit.html.erb
<h1>Editing Reason</h1>

<%= render 'form', reason: @reason %>

<%= link_to 'Show', @reason %> |
<%= link_to 'Back', reasons_path %>

app/views/reasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reasons</h1>

<table>
  <thead>
    <tr>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reasons.each do |reason| %>
      <tr>
        <td><%= reason.reason %></td>
        <td><%= link_to 'Show', reason %></td>
        <td><%= link_to 'Edit', edit_reason_path(reason) %></td>
        <td><%= link_to 'Destroy', reason, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reason', new_reason_path %>

app/views/reasons/new.html.erb
<h1>New Reason</h1>

<%= render 'form', reason: @reason %>

<%= link_to 'Back', reasons_path %>

app/views/reasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reason:</strong>
  <%= @reason.reason %>
</p>

<%= link_to 'Edit', edit_reason_path(@reason) %> |
<%= link_to 'Back', reasons_path %>